name: Build and Deploy Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # WAJIB untuk GitHub Pages (men-setup environment & token)
      - name: Configure Pages
        uses: actions/configure-pages@v5

      # Tambah CNAME (pastikan domain ini memang yang kamu pakai)
      - name: Ensure CNAME
        run: echo "www.wahyupriyonoo.my.id" > CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # kalau situs ada di folder lain (mis. /dist atau /docs), ubah path ini
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
